language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install tox-travis
  - pip install -r requirements/test_requirements.txt

script:
  - make test
